# Especificações dos prêmios por dia
# Caso não queira o prêmio específico no dia, deixe em 0.
# boxLvl será ignorada se boxQntd for 0.
prizes:
    day1:
        money: 500
        dust: 100
        box:
            qntd: 1
            lvl: 1
    day2:
        money: 500
        dust: 100
        box:
            qntd: 1
            lvl: 2
    day3:
        money: 500
        dust: 100
        box:
            qntd: 1
            lvl: 3
    day4:
        money: 500
        dust: 100
        box:
            qntd: 1
            lvl: 4
    day5:
        money: 500
        dust: 100
        box:
            qntd: 1
            lvl: 5
    day6:
        money: 500
        dust: 100
        box:
            qntd: 0
            lvl: 1
    day7:
        money: 500
        dust: 200
        box:
            qntd: 2
            lvl: 5
        special:
            enable: false
            text: ""
            command: ""
#
# Configurações de mensagens
#   Não funcionando ainda
#messages:
    
#
# Configurações de GUIs
#
guis:
    header:
        main: "&a&lSequência de Logins"
    itens:
        day1: "&2&l1º Dia"
        day2: "&2&l2º Dia"
        day3: "&2&l3º Dia"
        day4: "&2&l4º Dia"
        day5: "&2&l5º Dia"
        day6: "&2&l6º Dia"
        day7: "&2&l7º Dia"
        super: "&4&lPrêmio Especial"
        about: "&6&lSobre"